---
title: "Stats project"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(root.dir = "~/Desktop/'Stats'/")
```


# Setup

```{r}
library(ggplot2); library(tidyverse); library(GGally); library(survival); library(mice); library(table1); library(knitr)
```

```{r}
drug_dat <- read.csv('dataset', header = TRUE)
head(drug_dat)
```
```{r}
summary(drug_dat)
```

```{r}
drug_dat$gender <- as.factor(drug_dat$gender)
drug_dat$region <- as.factor(drug_dat$region)
drug_dat$residence <- as.factor(drug_dat$residence)
drug_dat$injecting_status <- as.factor(drug_dat$injecting_status)
drug_dat$housing_status <- as.factor(drug_dat$housing_status)
drug_dat$referral_source <- as.factor(drug_dat$referral_source)
drug_dat$rehab_success <- as.factor(drug_dat$rehab_success)
drug_dat$intervention <- as.factor(drug_dat$intervention)
drug_dat$last_obs_outcome <- as.factor(drug_dat$last_obs_outcome)
```

```{r}
summary(drug_dat)
#for ( i in seq(1,length( drug_dat ),1) ){           plot(drug_dat[,i],ylab=names(drug_dat[i]),type="l")}

```

```{r, echo=FALSE}
#ggpairs(drug_dat)
```

```{r}
ggplot(drug_dat, aes(x=intervention, y = duration_use, colour = intervention)) + geom_boxplot() + theme(legend.position = "none") + labs(title="Plot of duration of use by intervention type",
        x ="Intervention", y = "Duration of Use")
```

```{r}
ggplot(drug_dat, aes(x=intervention, y = duration_use, colour = intervention)) + geom_boxplot() + theme(legend.position = "none") + labs(title="Plot of duration of use by intervention type",
        x ="Intervention", y = "Duration of Use")
```


# Process the data

```{r}
ggplot(drug_dat, aes(x = injecting_status, y =wellbeing1yr, colour = injecting_status)) + geom_boxplot() + theme(legend.position = "none") + labs(title="Plot of wellbeing by Injecting Status",
        x ="Injecting Status", y = "Wellbeing")# Missing cannot be merged with another group -> drop values
```
```{r}
ggplot(drug_dat, aes(x = injecting_status, y =relapse_days, colour = injecting_status)) + geom_boxplot() + theme(legend.position = "none") + labs(title="Plot of relapse days by Injecting Status",
        x ="Injecting Status", y = "Observed days without relapse")# Missing cannot be merged with another group -> drop values
```





# Process the data

```{r}
ggplot(drug_dat, aes(x = injecting_status, y =wellbeing1yr, colour = injecting_status)) + geom_boxplot() + theme(legend.position = "none") + labs(title="Plot of wellbeing by Injecting Status",
        x ="Injecting Status", y = "Wellbeing")# Missing cannot be merged with another group -> drop values
```
```{r}
ggplot(drug_dat, aes(x = injecting_status, y =relapse_days, colour = injecting_status)) + geom_boxplot() + theme(legend.position = "none") + labs(title="Plot of wellbeing by Injecting Status",
        x ="Injecting Status", y = "Wellbeing")# Missing cannot be merged with another group -> drop values
```

```{r}
ggplot(drug_dat, aes(x = injecting_status, y =duration_use, colour = injecting_status)) + geom_boxplot() + theme(legend.position = "none") + labs(title="Plot of wellbeing by Injecting Status",
        x ="Injecting Status", y = "Wellbeing")# Missing cannot be merged with another group -> drop values
```

```{r}
t1 <- drug_dat %>% filter(intervention == 'peer mentoring')
t2 <- drug_dat %>% filter(intervention == 'standard of care')
summary(data3)
```

```{r}
# drug_dat <- drug_dat[which(drug_dat$last_study_obs != 0),]
drug_dat$housing_status <- relevel(drug_dat$housing_status, 'No problem')

drug_dat$intervention <- relevel(drug_dat$intervention, 'standard of care')

data2 <- drug_dat %>% filter(injecting_status != 'Missing')
data2$injecting_status <- relevel(data2$injecting_status, 'Never injected')
drug_dat$injecting_status <- relevel(drug_dat$injecting_status, 'Never injected')

data3 <- data2 %>% mutate(status = if_else(is.na(data2$relapse_days), 0, 1))
data3$relapse_days <- ifelse(is.na(data3$relapse_days), data3$last_study_obs, data3$relapse_days)
```


```{r}
tempData <- mice(data3,m=5,maxit=50,meth='pmm',seed=500)
summary(tempData)
data3 <- complete(tempData,1)
```

```{r}
dat1 <- drug_dat[,c(6,7,10)]
dat1$injecting_status[which(dat1$injecting_status == 'Missing')] <- NA
tempData1 <- mice(dat1,m=5,maxit=50,meth='pmm',seed=500)
data3$status <- as.factor(data3$status)
dat1 <- complete(tempData1,1)
```

```{r}
data3$status <- as.factor(data3$status)
table1(~. | intervention + injecting_status, data=data3)
```

# Aim 1


```{r}
summary(data2)
```


```{r}
aim1 <- glm(rehab_success ~ duration_use + gender, data = drug_dat, family = binomial(link=logit))
summary(aim1)
exp(coefficients(aim1))
exp(confint(aim1))
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
xtable(summary(aim1))
```
## Sens

```{r}
aim1 <- glm(rehab_success ~ injecting_status + duration_us data = dat1, family = binomial(link=logit))
summary(aim1)
exp(coefficients(aim1))
exp(confint(aim1))
modelFit1 <- with(tempData, glm(rehab_success ~ injecting_status, family = binomial(link=logit)))
summary(pool(modelFit1), conf.int = TRUE,conf.level = 0.95)
```

```{r}
#anova(data3$duration_use, data3$injecting_status)
plot(data3$injecting_status, data3$duration_use)
```

```{r}
aim1.1 <- glm(rehab_success ~ injecting_status, data = data3, family = binomial(link=logit))
summary(aim1.1)
aim1.2 <- glm(rehab_success ~ duration_use, data = data3, family = binomial(link=logit))
summary(aim1.2)
exp(coefficients(aim1.2))
exp(confint(aim1.2))
```


## Aim 2

```{r}
#data3 <- data3 %>% filter(last_obs_outcome != '(Other)')
```


```{r}
summary(data3$relapse_days)
length(data3$relapse_days)
```

```{r}
a <- survfit(Surv(relapse_days, status)  ~ intervention, data = data3) # need to do cox model so can timesplit at 410
summary(a)
plot.new
plot(b, col = 4:2,
main = "Kaplan-Meier Complementary Log Log Plot",
xlab = "Days", ylab = "Proportion Not Relapsing", fun = 'cloglog')
legend("topleft", c("Standard of Care", "Peer Mentor"), col = 4:1, lty = 1)
```

```{r}
a <- survfit(Surv(relapse_days, status)  ~ injecting_status, data = data3) # need to do cox model so can timesplit at 410
summary(a)
plot.new
plot(a, col = 4:2,
main = "Kaplan-Meier function",
xlab = "Days", ylab = "Proportion Not Relapsing")
legend("topright", c("Standard of Care", "Peer Mentor"), col = 4:1, lty = 1)
```

last study observation, not everyone at 720
```{r}
b <- coxph(Surv(relapse_days, status)  ~ intervention, data = data3) # need to do cox model as can 
summary(b)
cox.zph(b)
```

```{r}
data3$status <- as.numeric(data3$status)
split <- survSplit(Surv(relapse_days, status) ~ ., data = data3, cut = c(120), episode = 'period', zero = -0.0000000000000000000000000001)
split$period <- factor(split$period)

b <- coxph(Surv(relapse_days, status)  ~ intervention * strata(period) , data = split) # need to do cox model as can 
summary(b)
p1 <- cox.zph(b)
a
plot(p1)
```

```{r}
split <- survSplit(Surv(relapse_days, status) ~ ., data = data3, cut = 60, episode = 'period', zero = -0.0000000000000000000000000001)
split$period <- factor(split$period, 1:2, c('<60 days', '>60 days'))

b <- coxph(Surv(relapse_days, status)  ~ intervention * strata(period) + gender, data = split) # need to do cox model as can 
summary(b)
cox.zph(b)
```



# Aim 3

```{r}
hist(data3$wellbeing1yr)

t1 <- data3 %>% filter(intervention == 'peer mentoring')
t2 <- data3 %>% filter(intervention == 'standard of care')
length(which(t1$last_study_obs == 0))
```

```{r}
plot(t1$housing_status)
plot(t2$housing_status) # More of those with standard of care have housing problems 
```

```{r}
modelFit1 <- with(tempData, lm(wellbeing1yr ~ intervention))
summary(pool(modelFit1), conf.int = TRUE,conf.level = 0.95)
```

```{r}
modelFit1 <- with(tempData, lm(wellbeing1yr ~ intervention + rehab_success ))
summary(pool(modelFit1), conf.int = TRUE,conf.level = 0.95)
```

```{r}
p1 <- lm(wellbeing1yr ~ intervention, data = data2)
summary(p1)
confint(p1)
```